title: Tombstone - Grit & Determination
description: A Wild West Hack for Cairn RPG
theme: just-the-docs

url: https://alfndrate.github.io/

aux_links:
  Template Repository: https://github.com/Alfndrate/alfndrate.github.io
